spring.application.name=pertemuan11

# Konfigurasi Database PostgreSQL lokal (DBngin)
spring.datasource.url=jdbc:postgresql://localhost:5432/pertemuan11
spring.datasource.username=postgres
spring.datasource.password=

# Hibernate/JPA Settings (Otomatis membuat tabel users dan profile)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect